module.exports = {
  plugins: ['stylelint-prettier', 'stylelint-order'],
  rules: {
    'no-empty-source': true,
    'prettier/prettier': true,
    'block-no-empty': true,
    'order/properties-order': [
      'scss-mixin',
      'content',
      'position',
      'z-index',
      'top',
      'bottom',
      'left',
      'right',
      'display',
      'flex',
      'justify-content',
      'align-items',
      'width',
      'height',
      'max-width',
      'max-height',
      'padding',
      'padding-top',
      'padding-bottom',
      'padding-left',
      'padding-right',
      'margin',
      'margin-top',
      'margin-bottom',
      'margin-left',
      'margin-right',
      'font-family',
      'font-size',
      'font-weight',
      'line-height',
      'text-transform',
      'text-decoration',
      'text-align',
      'color',
      'background',
      'border'
    ]
  }
};
